### ISSUE TITLE
Weird interaction between observerlib and packmode that breaks mod loading

### ISSUE THREAD

**Issue by NickTimmermans26** [SkySom/PackMode#4]
After I added Observerlib to my modpack I started getting the error below.

```
[19:48:15] [main/INFO]: ModLauncher running: args [--username, MushWolf, --version, forge-35.1.7, --gameDir, D:\users\MushWolf\Documents\Curse\Minecraft\Instances\PackmodeBug, --assetsDir, D:\users\MushWolf\Documents\Curse\Minecraft\Install\assets, --assetIndex, 1.16, --uuid, 256d42b783304880a17617303a36a6b6, --accessToken, ????????, --userType, mojang, --versionType, release, --width, 1024, --height, 768, --launchTarget, fmlclient, --fml.forgeVersion, 35.1.7, --fml.mcVersion, 1.16.4, --fml.forgeGroup, net.minecraftforge, --fml.mcpVersion, 20201102.104115]
[19:48:15] [main/INFO]: ModLauncher 8.0.6+85+master.325de55 starting: java version 1.8.0_51 by Oracle Corporation
[19:48:15] [main/WARN]: LEGACY JDK DETECTED, SECURED JAR HANDLING DISABLED
[19:48:15] [main/INFO]: Added Lets Encrypt root certificates as additional trust
[19:48:15] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.2 Source=file:/D:/users/MushWolf/Documents/Curse/Minecraft/Install/libraries/org/spongepowered/mixin/0.8.2/mixin-0.8.2.jar Service=ModLauncher Env=CLIENT
[19:48:18] [main/INFO]: Launching target 'fmlclient' with arguments [--version, forge-35.1.7, --gameDir, D:\users\MushWolf\Documents\Curse\Minecraft\Instances\PackmodeBug, --assetsDir, D:\users\MushWolf\Documents\Curse\Minecraft\Install\assets, --uuid, 256d42b783304880a17617303a36a6b6, --username, MushWolf, --assetIndex, 1.16, --accessToken, ????????, --userType, mojang, --versionType, release, --width, 1024, --height, 768]
[19:48:19] [pool-3-thread-1/INFO]: Adding 'on_block_change' ASM patch...
[19:48:19] [pool-3-thread-1/INFO]: Added 'on_block_change' ASM patch!
[19:48:26] [Render thread/INFO]: Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', servicesHost='https://api.minecraftservices.com', name='PROD'
[19:48:27] [Render thread/INFO]: Setting user: MushWolf
[19:48:28] [Render thread/INFO]: Backend library: LWJGL version 3.2.2 build 10
[19:48:30] [modloading-worker-2/INFO]: Forge mod loading, version 35.1.7, for MC 1.16.4 with MCP 20201102.104115
[19:48:30] [modloading-worker-2/INFO]: MinecraftForge v35.1.7 Initialized
[19:48:34] [Render thread/INFO]: Narrator library for x64 successfully loaded
[19:48:34] [Render thread/INFO]: Reloading ResourceManager: Default, Mod Resources
[19:48:38] [Worker-Main-4/ERROR]: Exception caught during firing event: PackMode API not created yet!
	Index: 1
	Listeners:
		0: NORMAL
		1: net.minecraftforge.eventbus.EventBus$$Lambda$2899/886343183@4e224efa
java.lang.NullPointerException: PackMode API not created yet!
	at java.util.Objects.requireNonNull(Objects.java:228)
	at com.teamacronymcoders.packmode.api.PackModeAPI.getInstance(PackModeAPI.java:10)
	at com.teamacronymcoders.packmode.compat.crafttweaker.PackModePreprocessor.apply(PackModePreprocessor.java:37)
	at com.blamejared.crafttweaker.api.zencode.impl.FileAccessSingle.applyPreprocessors(FileAccessSingle.java:124)
	at com.blamejared.crafttweaker.api.zencode.impl.FileAccessSingle.<init>(FileAccessSingle.java:75)
	at com.blamejared.crafttweaker.api.CraftTweakerAPI.lambda$loadScripts$5(CraftTweakerAPI.java:113)
	at com.blamejared.crafttweaker.api.CraftTweakerAPI$$Lambda$3760/1942635715.apply(Unknown Source)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1374)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:512)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:502)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:576)
	at java.util.stream.AbstractPipeline.evaluateToArrayNode(AbstractPipeline.java:255)
	at java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:438)
	at com.blamejared.crafttweaker.api.CraftTweakerAPI.loadScripts(CraftTweakerAPI.java:117)
	at com.blamejared.crafttweaker.CraftTweaker.setup(CraftTweaker.java:145)
	at com.blamejared.crafttweaker.CraftTweaker$$Lambda$3184/950383234.accept(Unknown Source)
	at net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:247)
	at net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:239)
	at net.minecraftforge.eventbus.EventBus$$Lambda$2899/886343183.invoke(Unknown Source)
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:297)
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.acceptEvent(FMLModContainer.java:120)
	at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$4(ModContainer.java:121)
	at net.minecraftforge.fml.ModContainer$$Lambda$3067/203924386.run(Unknown Source)
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1618)
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1610)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1689)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)

[19:48:38] [Worker-Main-4/ERROR]: Caught exception during event FMLCommonSetupEvent dispatch for modid crafttweaker
java.lang.NullPointerException: PackMode API not created yet!
	at java.util.Objects.requireNonNull(Objects.java:228) ~[?:1.8.0_51]
	at com.teamacronymcoders.packmode.api.PackModeAPI.getInstance(PackModeAPI.java:10) ~[?:1.16.4-3.1.0]
	at com.teamacronymcoders.packmode.compat.crafttweaker.PackModePreprocessor.apply(PackModePreprocessor.java:37) ~[?:1.16.4-3.1.0]
	at com.blamejared.crafttweaker.api.zencode.impl.FileAccessSingle.applyPreprocessors(FileAccessSingle.java:124) ~[?:7.0.0.63]
	at com.blamejared.crafttweaker.api.zencode.impl.FileAccessSingle.<init>(FileAccessSingle.java:75) ~[?:7.0.0.63]
	at com.blamejared.crafttweaker.api.CraftTweakerAPI.lambda$loadScripts$5(CraftTweakerAPI.java:113) ~[?:7.0.0.63]
	at com.blamejared.crafttweaker.api.CraftTweakerAPI$$Lambda$3760/1942635715.apply(Unknown Source) ~[?:?]
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193) ~[?:1.8.0_51]
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1374) ~[?:1.8.0_51]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:512) ~[?:1.8.0_51]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:502) ~[?:1.8.0_51]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:576) ~[?:1.8.0_51]
	at java.util.stream.AbstractPipeline.evaluateToArrayNode(AbstractPipeline.java:255) ~[?:1.8.0_51]
	at java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:438) ~[?:1.8.0_51]
	at com.blamejared.crafttweaker.api.CraftTweakerAPI.loadScripts(CraftTweakerAPI.java:117) ~[?:7.0.0.63]
	at com.blamejared.crafttweaker.CraftTweaker.setup(CraftTweaker.java:145) ~[?:7.0.0.63]
	at com.blamejared.crafttweaker.CraftTweaker$$Lambda$3184/950383234.accept(Unknown Source) ~[?:?]
	at net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:247) ~[eventbus-3.0.5-service.jar:?]
	at net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:239) ~[eventbus-3.0.5-service.jar:?]
	at net.minecraftforge.eventbus.EventBus$$Lambda$2899/886343183.invoke(Unknown Source) ~[?:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:297) ~[eventbus-3.0.5-service.jar:?]
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.acceptEvent(FMLModContainer.java:120) [?:35.1]
	at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$4(ModContainer.java:121) [?:?]
	at net.minecraftforge.fml.ModContainer$$Lambda$3067/203924386.run(Unknown Source) [?:?]
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1618) [?:1.8.0_51]
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1610) [?:1.8.0_51]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289) [?:1.8.0_51]
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056) [?:1.8.0_51]
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1689) [?:1.8.0_51]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157) [?:1.8.0_51]
[19:48:38] [Forge Version Check/INFO]: [crafttweaker] Starting version check at https://updates.blamejared.com/get?n=crafttweaker&gv=1.16.4
[19:48:38] [Forge Version Check/INFO]: [crafttweaker] Found status: BETA_OUTDATED Current: 7.0.0.63 Target: 7.1.0.69
[19:48:38] [Forge Version Check/INFO]: [forge] Starting version check at https://files.minecraftforge.net/maven/net/minecraftforge/forge/promotions_slim.json
[19:48:38] [Forge Version Check/INFO]: [forge] Found status: AHEAD Current: 35.1.7 Target: null
[19:48:38] [Forge Version Check/INFO]: [jeitweaker] Starting version check at https://updates.blamejared.com/get?n=JEITweaker&gv=1.16.4
[19:48:38] [Forge Version Check/INFO]: [jeitweaker] Found status: BETA Current: 1.0.1.5 Target: 1.0.1.5
[19:48:39] [modloading-worker-1/FATAL]: Failed to complete lifecycle event COMMON_SETUP, 1 errors found
[19:48:39] [Worker-Main-5/ERROR]: Cowardly refusing to send event net.minecraftforge.client.event.TextureStitchEvent$Pre to a broken mod state
[19:48:39] [Worker-Main-5/ERROR]: Cowardly refusing to send event net.minecraftforge.client.event.TextureStitchEvent$Pre to a broken mod state
[19:48:39] [Worker-Main-5/ERROR]: Cowardly refusing to send event net.minecraftforge.client.event.TextureStitchEvent$Pre to a broken mod state
[19:48:39] [Worker-Main-5/ERROR]: Cowardly refusing to send event net.minecraftforge.client.event.TextureStitchEvent$Pre to a broken mod state
[19:48:39] [Worker-Main-5/ERROR]: Cowardly refusing to send event net.minecraftforge.client.event.TextureStitchEvent$Pre to a broken mod state
[19:48:39] [Worker-Main-5/ERROR]: Cowardly refusing to send event net.minecraftforge.client.event.TextureStitchEvent$Pre to a broken mod state
[19:48:39] [modloading-worker-1/ERROR]: Cowardly refusing to process mod state change request from ENQUEUE_IMC
[19:48:39] [modloading-worker-1/ERROR]: Cowardly refusing to process mod state change request from PROCESS_IMC
[19:48:39] [modloading-worker-1/ERROR]: Cowardly refusing to process mod state change request from COMPLETE
[19:48:41] [Render thread/INFO]: OpenAL initialized.
[19:48:41] [Render thread/INFO]: Sound engine started
[19:48:41] [Render thread/INFO]: Created: 256x128x0 jei:textures/atlas/gui.png-atlas
[19:48:41] [Render thread/ERROR]: Cowardly refusing to send event net.minecraftforge.client.event.TextureStitchEvent$Post to a broken mod state
[19:48:41] [Render thread/INFO]: Created: 1024x512x4 minecraft:textures/atlas/blocks.png-atlas
[19:48:42] [Render thread/ERROR]: Cowardly refusing to send event net.minecraftforge.client.event.TextureStitchEvent$Post to a broken mod state
[19:48:42] [Render thread/INFO]: Created: 256x128x4 minecraft:textures/atlas/signs.png-atlas
[19:48:42] [Render thread/ERROR]: Cowardly refusing to send event net.minecraftforge.client.event.TextureStitchEvent$Post to a broken mod state
[19:48:42] [Render thread/INFO]: Created: 512x512x4 minecraft:textures/atlas/banner_patterns.png-atlas
[19:48:42] [Render thread/ERROR]: Cowardly refusing to send event net.minecraftforge.client.event.TextureStitchEvent$Post to a broken mod state
[19:48:42] [Render thread/INFO]: Created: 512x512x4 minecraft:textures/atlas/shield_patterns.png-atlas
[19:48:42] [Render thread/ERROR]: Cowardly refusing to send event net.minecraftforge.client.event.TextureStitchEvent$Post to a broken mod state
[19:48:42] [Render thread/INFO]: Created: 256x256x4 minecraft:textures/atlas/chest.png-atlas
[19:48:42] [Render thread/ERROR]: Cowardly refusing to send event net.minecraftforge.client.event.TextureStitchEvent$Post to a broken mod state
[19:48:42] [Render thread/INFO]: Created: 512x256x4 minecraft:textures/atlas/beds.png-atlas
[19:48:42] [Render thread/ERROR]: Cowardly refusing to send event net.minecraftforge.client.event.TextureStitchEvent$Post to a broken mod state
[19:48:42] [Render thread/INFO]: Created: 512x256x4 minecraft:textures/atlas/shulker_boxes.png-atlas
[19:48:42] [Render thread/ERROR]: Cowardly refusing to send event net.minecraftforge.client.event.TextureStitchEvent$Post to a broken mod state
[19:48:42] [Render thread/ERROR]: Cowardly refusing to send event net.minecraftforge.client.event.ModelBakeEvent to a broken mod state
[19:48:43] [Render thread/INFO]: Created: 256x256x0 minecraft:textures/atlas/particles.png-atlas
[19:48:43] [Render thread/ERROR]: Cowardly refusing to send event net.minecraftforge.client.event.TextureStitchEvent$Post to a broken mod state
[19:48:43] [Render thread/INFO]: Created: 256x256x0 minecraft:textures/atlas/paintings.png-atlas
[19:48:43] [Render thread/ERROR]: Cowardly refusing to send event net.minecraftforge.client.event.TextureStitchEvent$Post to a broken mod state
[19:48:43] [Render thread/INFO]: Created: 128x128x0 minecraft:textures/atlas/mob_effects.png-atlas
[19:48:43] [Render thread/ERROR]: Cowardly refusing to send event net.minecraftforge.client.event.TextureStitchEvent$Post to a broken mod state
[19:48:43] [Render thread/FATAL]: Preparing crash report with UUID 380fdabf-0748-4f43-825f-0a51173c0c74
[19:48:43] [Render thread/INFO]: [net.minecraft.crash.CrashReport:func_85057_a:196]: Negative index in crash report handler (23/26)
[19:48:43] [Render thread/FATAL]: Crash report saved to D:\users\MushWolf\Documents\Curse\Minecraft\Instances\PackmodeBug\crash-reports\crash-2020-11-30_19.48.43-fml.txt
[19:49:03] [Render thread/INFO]: Stopping!
```

Versions:
CraftTweaker-1.16.4-7.0.0.63.jar
JEITweaker-1.16.4-1.0.1.5.jar
jei-1.16.4-7.6.0.58.jar
observerlib-1.16.4-1.4.4.jar
packmode-1.16.4-3.1.0.jar
forge-35.1.7

**Comment by NickTimmermans26** [comment]
BTW you can bypass the issue by removing the script from the scripts folder, and then readding them after the pack has loaded, but that won't go for when a modpack is actually released of course.

**Comment by NickTimmermans26** [comment]
This issue has been fixed by updating to a newer forge version, seeing as they are well passed version 7, can probably be closed.
